# Generated by Django 5.2.3 on 2025-11-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Info_given', 'info_given'), ('Meeting_scheduled', 'meeting_scheduled'), ('Meeting_done', 'meeting_done'), ('Not_reached', 'not_reached'), ('Sold', 'sold'), ('Not_sold', 'not_sold'), ('No_show', 'no_show')], default='new', max_length=20),
        ),
    ]
