# Generated by Django 5.2.3 on 2025-11-06 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'role': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='apps.operator'),
        ),
    ]
