# Generated by Django 5.2.3 on 2025-11-06 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_task_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='apps.operator'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sms', to='apps.operator'),
        ),
        migrations.AlterField(
            model_name='task',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='apps.operator'),
        ),
    ]
