# Generated by Django 5.2.3 on 2025-11-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_lead_operator_alter_sms_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='penalty',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='task_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='apps.task'),
        ),
    ]
