# Generated by Django 5.2.3 on 2025-11-06 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_operator_penalty_alter_operator_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='penalty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='apps.task'),
        ),
    ]
