# Generated by Django 5.2.3 on 2025-11-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_operator_penalty_alter_operator_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='penalty',
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=1)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='apps.lead')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='apps.operator')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
