# Generated by Django 5.2.3 on 2025-11-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_task_penalty_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='lead_id',
        ),
    ]
