# Generated by Django 5.2.8 on 2025-11-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_operator_lead_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='operator',
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leadlar'},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'verbose_name': 'Jarima', 'verbose_name_plural': 'Jarimalar'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='lead',
        ),
        migrations.AddField(
            model_name='lead',
            name='demo_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='operator_photos/'),
        ),
        migrations.AddField(
            model_name='operator',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('need_contact', 'Need Contact'), ('info_provided', 'Information Provided'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_cancelled', 'Meeting Cancelled'), ('could_not_contact', 'Could Not Contact'), ('sold', 'Sold'), ('not_sold', 'Not Sold'), ('did_not_show_up', 'Did Not Show Up')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='operator',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='operator',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operator',
            name='status',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Worker', 'Worker')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='apps.lead')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='apps.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.DeleteModel(
            name='SMS',
        ),
    ]
