# Generated by Django 5.2.8 on 2025-11-08 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_sms_lead_remove_sms_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_sms_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='apps.lead')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sms', to='apps.operator')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
