# Generated by Django 5.2.8 on 2025-11-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='updated_at',
        ),
    ]
